vich_uploader:
    db_driver: orm

    mappings:
        discussion_image:     
            uri_prefix: '%app.path.discussion_image%'    
            upload_destination: '%kernel.project_dir%/public%app.path.discussion_image%'  
            namer: Vich\UploaderBundle\Naming\UniqidNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
